using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace NaturalDateTime.CityIndex
{
    public class CountryCodeResolver
    {
        private static readonly Dictionary<string, string> _countryCodesToNames = new Dictionary<string, string>();

        static CountryCodeResolver()
        {
            InitializeCountryCodes();
        }
		
		public static string ResolveCountryCodeToCountryName(string countryCode)
        {
            return _countryCodesToNames[countryCode];
        }

        private static void InitializeCountryCodes()
        {
            _countryCodesToNames.Add("AD", "Andorra");
            _countryCodesToNames.Add("AE", "United Arab Emirates");
            _countryCodesToNames.Add("AF", "Afghanistan");
            _countryCodesToNames.Add("AG", "Antigua and Barbuda");
            _countryCodesToNames.Add("AI", "Anguilla");
            _countryCodesToNames.Add("AL", "Albania");
            _countryCodesToNames.Add("AM", "Armenia");
            _countryCodesToNames.Add("AO", "Angola");
            _countryCodesToNames.Add("AQ", "Antarctica");
            _countryCodesToNames.Add("AR", "Argentina");
            _countryCodesToNames.Add("AS", "American Samoa");
            _countryCodesToNames.Add("AT", "Austria");
            _countryCodesToNames.Add("AU", "Australia");
            _countryCodesToNames.Add("AW", "Aruba");
            _countryCodesToNames.Add("AX", "Åland Islands");
            _countryCodesToNames.Add("AZ", "Azerbaijan");
            _countryCodesToNames.Add("BA", "Bosnia and Herzegovina");
            _countryCodesToNames.Add("BB", "Barbados");
            _countryCodesToNames.Add("BD", "Bangladesh");
            _countryCodesToNames.Add("BE", "Belgium");
            _countryCodesToNames.Add("BF", "Burkina Faso");
            _countryCodesToNames.Add("BG", "Bulgaria");
            _countryCodesToNames.Add("BH", "Bahrain");
            _countryCodesToNames.Add("BI", "Burundi");
            _countryCodesToNames.Add("BJ", "Benin");
            _countryCodesToNames.Add("BL", "Saint Barthélemy");
            _countryCodesToNames.Add("BM", "Bermuda");
            _countryCodesToNames.Add("BN", "Brunei Darussalam");
            _countryCodesToNames.Add("BO", "Bolivia");
            _countryCodesToNames.Add("BQ", "Sint Eustatius");
            _countryCodesToNames.Add("BR", "Brazil");
            _countryCodesToNames.Add("BS", "Bahamas");
            _countryCodesToNames.Add("BT", "Bhutan");
            _countryCodesToNames.Add("BV", "Bouvet Island");
            _countryCodesToNames.Add("BW", "Botswana");
            _countryCodesToNames.Add("BY", "Belarus");
            _countryCodesToNames.Add("BZ", "Belize");
            _countryCodesToNames.Add("CA", "Canada");
            _countryCodesToNames.Add("CC", "Cocos (Keeling) Islands");
            _countryCodesToNames.Add("CD", "Congo");
            _countryCodesToNames.Add("CF", "Central African Republic");
            _countryCodesToNames.Add("CG", "Congo");
            _countryCodesToNames.Add("CH", "Switzerland");
            _countryCodesToNames.Add("CI", "Côte d'Ivoire");
            _countryCodesToNames.Add("CK", "Cook Islands");
            _countryCodesToNames.Add("CL", "Chile");
            _countryCodesToNames.Add("CM", "Cameroon");
            _countryCodesToNames.Add("CN", "China");
            _countryCodesToNames.Add("CO", "Colombia");
            _countryCodesToNames.Add("CR", "Costa Rica");
            _countryCodesToNames.Add("CS", "Serbia and Montenegro");
            _countryCodesToNames.Add("CU", "Cuba");
            _countryCodesToNames.Add("CV", "Cape Verde");
            _countryCodesToNames.Add("CW", "Curaçao");
            _countryCodesToNames.Add("CX", "Christmas Island");
            _countryCodesToNames.Add("CY", "Cyprus");
            _countryCodesToNames.Add("CZ", "Czech Republic");
            _countryCodesToNames.Add("DE", "Germany");
            _countryCodesToNames.Add("DJ", "Djibouti");
            _countryCodesToNames.Add("DK", "Denmark");
            _countryCodesToNames.Add("DM", "Dominica");
            _countryCodesToNames.Add("DO", "Dominican Republic");
            _countryCodesToNames.Add("DZ", "Algeria");
            _countryCodesToNames.Add("EC", "Ecuador");
            _countryCodesToNames.Add("EE", "Estonia");
            _countryCodesToNames.Add("EG", "Egypt");
            _countryCodesToNames.Add("EH", "Western Sahara");
            _countryCodesToNames.Add("ER", "Eritrea");
            _countryCodesToNames.Add("ES", "Spain");
            _countryCodesToNames.Add("ET", "Ethiopia");
            _countryCodesToNames.Add("FI", "Finland");
            _countryCodesToNames.Add("FJ", "Fiji");
            _countryCodesToNames.Add("FK", "Falkland Islands (Malvinas)");
            _countryCodesToNames.Add("FM", "Micronesia");
            _countryCodesToNames.Add("FO", "Faroe Islands");
            _countryCodesToNames.Add("FR", "France");
            _countryCodesToNames.Add("GA", "Gabon");
            _countryCodesToNames.Add("GB", "United Kingdom");
            _countryCodesToNames.Add("GD", "Grenada");
            _countryCodesToNames.Add("GE", "Georgia");
            _countryCodesToNames.Add("GF", "French Guiana");
            _countryCodesToNames.Add("GG", "Guernsey");
            _countryCodesToNames.Add("GH", "Ghana");
            _countryCodesToNames.Add("GI", "Gibraltar");
            _countryCodesToNames.Add("GL", "Greenland");
            _countryCodesToNames.Add("GM", "Gambia");
            _countryCodesToNames.Add("GN", "Guinea");
            _countryCodesToNames.Add("GP", "Guadeloupe");
            _countryCodesToNames.Add("GQ", "Equatorial Guinea");
            _countryCodesToNames.Add("GR", "Greece");
            _countryCodesToNames.Add("GS", "South Georgia and the South Sandwich Islands");
            _countryCodesToNames.Add("GT", "Guatemala");
            _countryCodesToNames.Add("GU", "Guam");
            _countryCodesToNames.Add("GW", "Guinea-Bissau");
            _countryCodesToNames.Add("GY", "Guyana");
            _countryCodesToNames.Add("HK", "Hong Kong");
            _countryCodesToNames.Add("HM", "Heard Island and McDonald Islands");
            _countryCodesToNames.Add("HN", "Honduras");
            _countryCodesToNames.Add("HR", "Croatia");
            _countryCodesToNames.Add("HT", "Haiti");
            _countryCodesToNames.Add("HU", "Hungary");
            _countryCodesToNames.Add("ID", "Indonesia");
            _countryCodesToNames.Add("IE", "Ireland");
            _countryCodesToNames.Add("IL", "Israel");
            _countryCodesToNames.Add("IM", "Isle of Man");
            _countryCodesToNames.Add("IN", "India");
            _countryCodesToNames.Add("IO", "British Indian Ocean Territory");
            _countryCodesToNames.Add("IQ", "Iraq");
            _countryCodesToNames.Add("IR", "Iran");
            _countryCodesToNames.Add("IS", "Iceland");
            _countryCodesToNames.Add("IT", "Italy");
            _countryCodesToNames.Add("JE", "Jersey");
            _countryCodesToNames.Add("JM", "Jamaica");
            _countryCodesToNames.Add("JO", "Jordan");
            _countryCodesToNames.Add("JP", "Japan");
            _countryCodesToNames.Add("KE", "Kenya");
            _countryCodesToNames.Add("KG", "Kyrgyzstan");
            _countryCodesToNames.Add("KH", "Cambodia");
            _countryCodesToNames.Add("KI", "Kiribati");
            _countryCodesToNames.Add("KM", "Comoros");
            _countryCodesToNames.Add("KN", "Saint Kitts and Nevis");
            _countryCodesToNames.Add("KP", "Democratic People's Republic of Korea");
            _countryCodesToNames.Add("KR", "Republic of Korea");
            _countryCodesToNames.Add("KW", "Kuwait");
            _countryCodesToNames.Add("KY", "Cayman Islands");
            _countryCodesToNames.Add("KZ", "Kazakhstan");
            _countryCodesToNames.Add("LA", "Lao People's Democratic Republic");
            _countryCodesToNames.Add("LB", "Lebanon");
            _countryCodesToNames.Add("LC", "Saint Lucia");
            _countryCodesToNames.Add("LI", "Liechtenstein");
            _countryCodesToNames.Add("LK", "Sri Lanka");
            _countryCodesToNames.Add("LR", "Liberia");
            _countryCodesToNames.Add("LS", "Lesotho");
            _countryCodesToNames.Add("LT", "Lithuania");
            _countryCodesToNames.Add("LU", "Luxembourg");
            _countryCodesToNames.Add("LV", "Latvia");
            _countryCodesToNames.Add("LY", "Libyan Arab Jamahiriya");
            _countryCodesToNames.Add("MA", "Morocco");
            _countryCodesToNames.Add("MC", "Monaco");
            _countryCodesToNames.Add("MD", "Republic of Moldova");
            _countryCodesToNames.Add("ME", "Montenegro");
            _countryCodesToNames.Add("MF", "Saint Martin (French part)");
            _countryCodesToNames.Add("MG", "Madagascar");
            _countryCodesToNames.Add("MH", "Marshall Islands");
            _countryCodesToNames.Add("MK", "Macedonia");
            _countryCodesToNames.Add("ML", "Mali");
            _countryCodesToNames.Add("MM", "Myanmar");
            _countryCodesToNames.Add("MN", "Mongolia");
            _countryCodesToNames.Add("MO", "Macao");
            _countryCodesToNames.Add("MP", "Northern Mariana Islands");
            _countryCodesToNames.Add("MQ", "Martinique");
            _countryCodesToNames.Add("MR", "Mauritania");
            _countryCodesToNames.Add("MS", "Montserrat");
            _countryCodesToNames.Add("MT", "Malta");
            _countryCodesToNames.Add("MU", "Mauritius");
            _countryCodesToNames.Add("MV", "Maldives");
            _countryCodesToNames.Add("MW", "Malawi");
            _countryCodesToNames.Add("MX", "Mexico");
            _countryCodesToNames.Add("MY", "Malaysia");
            _countryCodesToNames.Add("MZ", "Mozambique");
            _countryCodesToNames.Add("NA", "Namibia");
            _countryCodesToNames.Add("NC", "New Caledonia");
            _countryCodesToNames.Add("NE", "Niger");
            _countryCodesToNames.Add("NF", "Norfolk Island");
            _countryCodesToNames.Add("NG", "Nigeria");
            _countryCodesToNames.Add("NI", "Nicaragua");
            _countryCodesToNames.Add("NL", "Netherlands");
            _countryCodesToNames.Add("NO", "Norway");
            _countryCodesToNames.Add("NP", "Nepal");
            _countryCodesToNames.Add("NR", "Nauru");
            _countryCodesToNames.Add("NU", "Niue");
            _countryCodesToNames.Add("NZ", "New Zealand");
            _countryCodesToNames.Add("OM", "Oman");
            _countryCodesToNames.Add("PA", "Panama");
            _countryCodesToNames.Add("PE", "Peru");
            _countryCodesToNames.Add("PF", "French Polynesia");
            _countryCodesToNames.Add("PG", "Papua New Guinea");
            _countryCodesToNames.Add("PH", "Philippines");
            _countryCodesToNames.Add("PK", "Pakistan");
            _countryCodesToNames.Add("PL", "Poland");
            _countryCodesToNames.Add("PM", "Saint Pierre and Miquelon");
            _countryCodesToNames.Add("PN", "Pitcairn");
            _countryCodesToNames.Add("PR", "Puerto Rico");
            _countryCodesToNames.Add("PS", "Occupied Palestinian Territory");
            _countryCodesToNames.Add("PT", "Portugal");
            _countryCodesToNames.Add("PW", "Palau");
            _countryCodesToNames.Add("PY", "Paraguay");
            _countryCodesToNames.Add("QA", "Qatar");
            _countryCodesToNames.Add("RE", "Réunion");
            _countryCodesToNames.Add("RO", "Romania");
            _countryCodesToNames.Add("RS", "Serbia");
            _countryCodesToNames.Add("RU", "Russian Federation");
            _countryCodesToNames.Add("RW", "Rwanda");
            _countryCodesToNames.Add("SA", "Saudi Arabia");
            _countryCodesToNames.Add("SB", "Solomon Islands");
            _countryCodesToNames.Add("SC", "Seychelles");
            _countryCodesToNames.Add("SD", "Sudan");
            _countryCodesToNames.Add("SE", "Sweden");
            _countryCodesToNames.Add("SG", "Singapore");
            _countryCodesToNames.Add("SH", "Saint Helena, Ascension and Tristan da Cunha");
            _countryCodesToNames.Add("SI", "Slovenia");
            _countryCodesToNames.Add("SJ", "Svalbard and Jan Mayen");
            _countryCodesToNames.Add("SK", "Slovakia");
            _countryCodesToNames.Add("SL", "Sierra Leone");
            _countryCodesToNames.Add("SM", "San Marino");
            _countryCodesToNames.Add("SN", "Senegal");
            _countryCodesToNames.Add("SO", "Somalia");
            _countryCodesToNames.Add("SR", "Suriname");
            _countryCodesToNames.Add("SS", "South Sudan");
            _countryCodesToNames.Add("ST", "Sao Tome and Principe");
            _countryCodesToNames.Add("SV", "El Salvador");
            _countryCodesToNames.Add("SX", "Sint Maarten");
            _countryCodesToNames.Add("SY", "Syrian Arab Republic");
            _countryCodesToNames.Add("SZ", "Swaziland");
            _countryCodesToNames.Add("TC", "Turks and Caicos Islands");
            _countryCodesToNames.Add("TD", "Chad");
            _countryCodesToNames.Add("TF", "French Southern Territories");
            _countryCodesToNames.Add("TG", "Togo");
            _countryCodesToNames.Add("TH", "Thailand");
            _countryCodesToNames.Add("TJ", "Tajikistan");
            _countryCodesToNames.Add("TK", "Tokelau");
            _countryCodesToNames.Add("TL", "Timor-Leste");
            _countryCodesToNames.Add("TM", "Turkmenistan");
            _countryCodesToNames.Add("TN", "Tunisia");
            _countryCodesToNames.Add("TO", "Tonga");
            _countryCodesToNames.Add("TR", "Turkey");
            _countryCodesToNames.Add("TT", "Trinidad and Tobago");
            _countryCodesToNames.Add("TV", "Tuvalu");
            _countryCodesToNames.Add("TW", "Taiwan");
            _countryCodesToNames.Add("TZ", "Tanzania");
            _countryCodesToNames.Add("UA", "Ukraine");
            _countryCodesToNames.Add("UG", "Uganda");
            _countryCodesToNames.Add("UM", "United States Minor Outlying Islands");
            _countryCodesToNames.Add("US", "United States");
            _countryCodesToNames.Add("UY", "Uruguay");
            _countryCodesToNames.Add("UZ", "Uzbekistan");
            _countryCodesToNames.Add("VA", "Holy See (Vatican City State)");
            _countryCodesToNames.Add("VC", "Saint Vincent and the Grenadines");
            _countryCodesToNames.Add("VE", "Venezuela");
            _countryCodesToNames.Add("VG", "British Virgin Islands");
            _countryCodesToNames.Add("VI", "U.S. Virgin Islands");
            _countryCodesToNames.Add("VN", "Viet Nam");
            _countryCodesToNames.Add("VU", "Vanuatu");
            _countryCodesToNames.Add("WF", "Wallis and Futuna");
            _countryCodesToNames.Add("WS", "Samoa");
            _countryCodesToNames.Add("XK", "Kosovo");
            _countryCodesToNames.Add("YE", "Yemen");
            _countryCodesToNames.Add("YT", "Mayotte");
            _countryCodesToNames.Add("YU", "Yugoslavia");
            _countryCodesToNames.Add("ZA", "South Africa");
            _countryCodesToNames.Add("ZM", "Zambia");
            _countryCodesToNames.Add("ZR", "Zaire ");
            _countryCodesToNames.Add("ZW", "Zimbabwe");
        }
    }
}
